spring.application.name=test1

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=jdbc:mysql://localhost:3306/javaee?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false

spring.datasource.username=root

spring.datasource.password=wsws0412

# MyBatis ??????
# ??XML??????????SQL??????
mybatis.mapper-locations=classpath:mapper/*.xml
# ?????????XML?????????
mybatis.type-aliases-package=com.example.test1.entity